### ISSUE TITLE
Don't mention the user that moved the issue

### ISSUE THREAD

**Issue by Ben3eeE** [dessant/move-issues#1]
Hey,

This looks like a great bot and we are planning to use it in the Atom org. However it would be great if the bot does not @mention the user that moved the issue because that makes you "participating" in the issue/notifications. Sometimes we want to move an issue because it's in the wrong repo but don't have any additional insight and questions. In those cases we would like normal notifications not "participating" ones.

Would you be open to a pull request that adds an option to disable the "by @" part of the bottom of the issue?

![image](https://user-images.githubusercontent.com/1058982/39087812-c79cfe26-45a6-11e8-9aa6-99d21f8ceb83.png)

**Comment by Ben3eeE** [comment]
Yeah that sounds good 👍 Either remove the `@` or surround it with backticks to prevent the mention 🙂

**Comment by dessant** [comment]
Issue, comment, and command author mentions can be disabled with `mentionAuthors: false`.

Glitch is not willing to deploy the latest version after the import, and the bot is down. I'll update you here when it comes back up.

**Comment by dessant** [comment]
The bot is up now.

**Comment by Ben3eeE** [comment]
@dessant Thank you so much :bowing_man: :bowing_man:
