### ISSUE TITLE
GitHub has shipped an issue moving capability

### ISSUE THREAD

**Issue by gpadak** [dessant/move-issues#10]
Today GitHub shipped issue transfers as a public beta on GitHub.com https://blog.github.com/changelog/2018-10-30-issue-transfer/. This allows a repository administrator to transfer an issue to another repository where the user also has repository administration privileges.

Check out the Help Docs for more details: https://help.github.com/articles/transferring-an-issue-to-another-repository/.

**Comment by dessant** [comment]
That's awesome, thanks for letting me know!
