### ISSUE TITLE
Also move labels

### ISSUE THREAD

**Issue by dentarg** [dessant/move-issues#5]
Is it possible for the bot to apply the same labels (if the exist on the target repo) that the original issue had?

**Comment by dessant** [comment]
This could be useful, I'll look into it. Thanks for the suggestion!

**Comment by m1dst** [comment]
This would be great!  Already found a tool to copy labels from one repo to another.  Just holding off moving the issues now as this will be a huge task to manually update all the issues I'm about to move.

**Comment by dessant** [comment]
I'll add the feature next week, it should be easy to implement.

**Comment by dessant** [comment]
Labels that also exist on the target repository are now moved by default. The feature can be disabled with the `moveLabels` config option. The new version has been deployed on the hosted instance.

**Comment by dentarg** [comment]
Thanks @dessant, it will be useful
